version: "3.7"

services:

  frontend:
    build:
      context: ./app
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - PORT=80
    expose:
      - "80"
    ports:
      - "5050:80"