version: "3.7"

services:
    
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL_MYSQL=mysql://dbuser:1234@mysql:3306/core_db
      - SCHEMA=public
      - PORT=80
    expose:
      - "80"
    ports:
      - "3000:80"
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--" , "npm","start"]


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: core_db
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql 

